### ISSUE TITLE
How to fix files on a directory recursively? ( WIN 10 )

### ISSUE THREAD

**Issue by erenpal** [loichyan/nerdfix#26]
.\nerdfix.exe check --recursive "C:\Program Files\Neovim"

Does checking on a directory but

.\nerdfix.exe fix --recursive "C:\Program Files\Neovim"
gives error
←[33m WARN←[0m Output path is ignored when `--recursive`: \Program Files\Neovim
←[31mERROR←[0m Failed when traversing directories, IO error for operation on C: The system cannot find the file specified. (os error 2)

**Comment by loichyan** [comment]
ahhh, that’s a bug: nerdfix supports save fixed file to a different path through the `nerdfix fix input:output` syntax, so `C:\Program Files\Neovim` is considered as two paths, `C` and `\Program Files\Neovim`. I will fix this later. Currently, you can `cd C:\Program Files\Neovim` and `nerdfix fix —recursive .` for a workaround.
