### ISSUE TITLE
Autofix yes flag does not seem to be working

### ISSUE THREAD

**Issue by mohkale** [loichyan/nerdfix#3]
Hi,

I'm using 

```text
$ nerdfix --version
nerdfix 0.2.3
cheat-sheet: 634e151
```

To autofix a file containing icons at /tmp/all2 by running `nerdfix fix -y /tmp/all2` but it seems to prompt me interactively no matter what I try.

**Comment by loichyan** [comment]
Should be fixed in #4. The `--yes` argument is used to confirm whether to write patched content, which is a bit confusing. So I replaced it with `--write` and added `--select-first`, combining the two should skip all possible prompts.
