### ISSUE TITLE
Add support for checking folders

### ISSUE THREAD

**Issue by smjonas** [loichyan/nerdfix#5]
Thanks for this useful project! What do you think about adding support for folders when using the `nerdfix check` / `nerdfix fix` commands in which case the command would be applied to all the files in the directory recursively? This would allow something like `nerdfix check ~/.local/share/nvim` to check all Nvim configuration files.

**Comment by loichyan** [comment]
I added `--recursive` in #6, but it's recommended to use `nerdfix check $(fd -t f . ~/.local/share/nvim)` to exclude some hidden directories (like `.git`, which contains many binary files and causes many non-UTF-8 errors).
